<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>CheckmkDesktopNotifier.App.MacOS</RootNamespace>
    <AssemblyName>CheckmkDesktopNotifier.MacOS</AssemblyName>
    <ApplicationTitle>Checkmk Desktop Notifier</ApplicationTitle>
    <Version>1.3.0-beta.1</Version>
    <AssemblyVersion>1.3.0.0</AssemblyVersion>
    <FileVersion>1.3.0.0</FileVersion>
    <InformationalVersion>1.3.0-beta.1</InformationalVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RuntimeIdentifiers>osx-x64;osx-arm64</RuntimeIdentifiers>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <BuiltInComInteropSupport>false</BuiltInComInteropSupport>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CheckmkDesktopNotifier.Core\CheckmkDesktopNotifier.Core.csproj" />
    <ProjectReference Include="..\CheckmkDesktopNotifier.Infrastructure\CheckmkDesktopNotifier.Infrastructure.csproj" />
    <ProjectReference Include="..\CheckmkDesktopNotifier.Platform.MacOS\CheckmkDesktopNotifier.Platform.MacOS.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\notifier.wav" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.8" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.8" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.8" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.8" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

</Project>
