using System.Globalization;
using System.Resources;

namespace CheckmkDesktopNotifier.App.Localization;

public interface ILocalizationService
{
    CultureInfo Culture { get; }

    void SetCulture(CultureInfo culture);

    string CompactBarTitle { get; }
    string NewLabel { get; }
    string CriticalLabel { get; }
    string WarningLabel { get; }
    string UnknownLabel { get; }
    string LastCheckLabel { get; }
    string LastCheckUnknown { get; }
    string MarkAllNewAsSeen { get; }
    string MarkAsSeen { get; }
    string MarkAsUnseen { get; }
    string OpenInCheckmk { get; }
    string Seen { get; }
    string Acknowledged { get; }
    string AcknowledgedTooltip { get; }
    string Downtime { get; }
    string DowntimeTooltip { get; }
    string HostKind { get; }
    string NewSection { get; }
    string CriticalSection { get; }
    string WarningSection { get; }
    string UnknownSection { get; }
    string NoNewProblems { get; }
    string NoProblems { get; }
    string ProblemListTitle { get; }
    string SeverityCritical { get; }
    string SeverityWarning { get; }
    string SeverityUnknown { get; }
    string ConnectionConnected { get; }
    string ConnectionRefreshing { get; }
    string ConnectionError { get; }
    string ConnectionSetupRequired { get; }
    string ConnectionInitializing { get; }
    string Settings { get; }
    string SettingsTitle { get; }
    string SettingsIntro { get; }
    string SettingsServerUrl { get; }
    string SettingsSite { get; }
    string SettingsUsername { get; }
    string SettingsSecret { get; }
    string SettingsSecretHint { get; }
    string SettingsPollInterval { get; }
    string SettingsTestConnection { get; }
    string SettingsSave { get; }
    string SettingsCancel { get; }
    string SettingsReset { get; }
    string SettingsResetConfirm { get; }
    string TestSuccess { get; }
    string TestUnauthorized { get; }
    string TestForbidden { get; }
    string TestUnreachable { get; }
    string TestTimeout { get; }
    string TestTls { get; }
    string TestInvalidConfiguration { get; }
    string TestUnexpectedApi { get; }
    string TestUnavailable { get; }
    string TestServicesReachable { get; }
    string TestHostsReachable { get; }
    string SettingsSaved { get; }
    string SettingsValidationFailed { get; }
    string TestNotificationSound { get; }
    string SoundSection { get; }
    string SoundDefault { get; }
    string SoundCustomWav { get; }
    string SoundChooseWav { get; }
    string SoundVolume { get; }
    string SoundRestoreDefault { get; }
    string SoundMute { get; }
    string SoundInvalidWav { get; }
    string SoundWavFilter { get; }
    string SettingsTabGeneral { get; }
    string SettingsTabConnection { get; }
    string SettingsTabNotifications { get; }
    string SettingsStartWithWindows { get; }
    string SettingsAutostartFailed { get; }
    string SettingsNotificationsIntro { get; }
    string FilterAll { get; }
    string FilterNew { get; }
    string FilterCritical { get; }
    string FilterWarning { get; }
    string FilterUnknown { get; }
    string FilterTaken { get; }
    string EmptyFilterAll { get; }
    string EmptyFilterNew { get; }
    string EmptyFilterCritical { get; }
    string EmptyFilterWarning { get; }
    string EmptyFilterUnknown { get; }
    string EmptyFilterTaken { get; }
    string EmptyFilterSearch { get; }
    string SearchPlaceholder { get; }
    string TakenLabel { get; }
    string MenuConnectionSettings { get; }
    string MenuHelpAbout { get; }
    string MenuExit { get; }
    string MenuOpen { get; }
    string MenuMuteSound { get; }
    string MenuUnmuteSound { get; }
    string MenuHideToTray { get; }
    string AboutTitle { get; }
    string AboutDescription { get; }
    string AboutVersion { get; }
    string AboutAuthor { get; }
    string AboutGitHub { get; }
    string AboutClose { get; }
    string Take { get; }
    string Taking { get; }
    string Taken { get; }
    string TakenByFormat { get; }
    string EnableTake { get; }
    string DisplayName { get; }
    string TeamCoordination { get; }
    string TeamCoordinationHint { get; }
    string TakeConfirmTitle { get; }
    string TakeConfirmBody { get; }
    string TakeCouldNot { get; }
    string TakeForbidden { get; }
    string TakeAwaitingRefresh { get; }
}
